## Arrays vs. Lists

In [1]:
import numpy as np

In [2]:
List = [1,2,3]

In [3]:
Array = np.array([1,2,3])

In [4]:
for element in List:
    print(element)

1
2
3


In [5]:
for element in Array:
    print(element)

1
2
3


In [6]:
List.append(4)

In [7]:
List

[1, 2, 3, 4]

In [8]:
Array.append(4)

AttributeError: ignored

In [9]:
List + [5]

[1, 2, 3, 4, 5]

In [10]:
Array + np.array([4]) # Broadcasting

array([5, 6, 7])

In [12]:
Array + np.array([4,5,6])

array([5, 7, 9])

In [13]:
Array + np.array([4,5])

ValueError: ignored

In [14]:
2 * Array

array([2, 4, 6])

In [15]:
2 * List

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
List + List

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
L2 = []
for element in List:
    L2.append(element+3)

In [19]:
L2

[4, 5, 6, 7]

In [20]:
L2 = [e+3 for e in List]

In [21]:
L2

[4, 5, 6, 7]

In [23]:
List**2

TypeError: ignored

In [24]:
L2 = [e**2 for e in List]

In [25]:
L2

[1, 4, 9, 16]

In [26]:
Array **2 

array([1, 4, 9])

In [27]:
np.sqrt(Array)

array([1.        , 1.41421356, 1.73205081])

In [28]:
np.log(Array)

array([0.        , 0.69314718, 1.09861229])

In [29]:
np.exp(Array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [30]:
np.tanh(Array)

array([0.76159416, 0.96402758, 0.99505475])

# Dot Product

In [31]:
a = np.array([1,2])
b = np.array([3,4])

In [33]:
dot = 0
for e,f in zip(a,b):
    dot += e * f
print(dot)

11


In [36]:
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
print(dot)

11


In [37]:
a * b # element wise multiplication

array([3, 8])

In [38]:
np.sum(a*b)

11

In [39]:
(a*b).sum()

11

In [41]:
np.dot(a, b)

11

In [42]:
a.dot(b)

11

In [43]:
a @ b

11

In [46]:
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

In [47]:
np.linalg.norm(a)

2.23606797749979

In [49]:
cosangle = a.dot(b)/(np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [50]:
angle = np.arccos(cosangle)
angle # radians

0.17985349979247847

# Speed Test

In [54]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a,b):
    result = 0
    for e,f in zip(a,b):
        result += e * f
    return result

t0 = datetime.now()
for t in range(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 60.562502538002356


# Matrices

In [56]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [57]:
L[0]

[1, 2]

In [58]:
L[0][1]

2

In [59]:
A = np.array([[1,2],[3,4]])

In [60]:
A

array([[1, 2],
       [3, 4]])

In [61]:
A[0][1]

2

In [62]:
A[0,1]

2

In [63]:
A[:,1]

array([2, 4])

In [64]:
A[:,0]

array([1, 3])

In [65]:
A.T

array([[1, 3],
       [2, 4]])

In [66]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [67]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [68]:
B = np.array([[1,2,3],[4,5,6]])

In [69]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [70]:
A.dot(B.T)

ValueError: ignored

In [71]:
np.linalg.det(A)

-2.0000000000000004

In [72]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [73]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [74]:
np.trace(A)

5

In [75]:
np.diag(A)

array([1, 4])

In [76]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [77]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [78]:
lam, v = np.linalg.eig(A)

In [80]:
v[:,0] * lam[0] == A @ v[:,0]

array([ True, False])

In [81]:
v[:,0] * lam[0] , A @ v[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [82]:
np.allclose(v[:,0] * lam[0], A @ v[:,0])

True

In [83]:
np.allclose(v @ np.diag(lam), A @ v)

True

# Linear Systems

In [85]:
A = np.array([[1,1],[1.5, 4]])
b = np.array([2200, 5050])

In [86]:
np.linalg.solve(A,b)

array([1500.,  700.])

In [87]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

# Generating Data

In [88]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [90]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [91]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.random.random()

0.33162884719840147

In [93]:
np.random.random((2,3))

array([[0.47212816, 0.53640115, 0.0854955 ],
       [0.11679234, 0.37112066, 0.85164973]])

In [96]:
np.random.randn(2,3)

array([[-1.12297338,  0.72550457, -0.79448816],
       [-0.72482613,  1.31293352, -0.74799232]])

In [97]:
R = np.random.randn(10000)

In [98]:
R.mean()

0.01213114199485837

In [100]:
np.mean(R)

0.01213114199485837

In [101]:
np.median(R)

0.007381121898325726

In [102]:
R.var()

0.9904633106631225

In [103]:
np.std(R)

0.9952202322416493

In [104]:
R.std()

0.9952202322416493

In [106]:
np.sqrt(R.var())

0.9952202322416493

In [107]:
R = np.random.randn(10000, 3)

In [108]:
R.mean(axis=0)

array([-0.00248894, -0.00454532, -0.01456656])

In [109]:
R.mean(axis=1).shape

(10000,)

In [110]:
np.cov(R)

array([[ 0.70739567,  0.01939022, -0.24298613, ...,  0.13458952,
        -0.15747708, -0.78795803],
       [ 0.01939022,  0.01088325,  0.10869589, ..., -0.00284114,
         0.05288681,  0.03883526],
       [-0.24298613,  0.10869589,  1.36895459, ..., -0.11900244,
         0.69154676,  0.94411128],
       ...,
       [ 0.13458952, -0.00284114, -0.11900244, ...,  0.0297267 ,
        -0.06604804, -0.18804158],
       [-0.15747708,  0.05288681,  0.69154676, ..., -0.06604804,
         0.35116034,  0.50936593],
       [-0.78795803,  0.03883526,  0.94411128, ..., -0.18804158,
         0.50936593,  1.2305087 ]])

In [111]:
np.cov(R).shape

(10000, 10000)

In [112]:
np.cov(R.T)

array([[ 0.97932791, -0.01568764,  0.0070954 ],
       [-0.01568764,  1.00662736, -0.0169654 ],
       [ 0.0070954 , -0.0169654 ,  0.98834603]])

In [113]:
np.cov(R, rowvar=False)

array([[ 0.97932791, -0.01568764,  0.0070954 ],
       [-0.01568764,  1.00662736, -0.0169654 ],
       [ 0.0070954 , -0.0169654 ,  0.98834603]])

In [114]:
np.random.randint(0,10,(3,3))

array([[3, 8, 4],
       [6, 9, 0],
       [4, 6, 1]])

In [115]:
np.random.choice(10, size=(3,3))

array([[0, 5, 0],
       [3, 5, 2],
       [8, 3, 1]])